# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
 name: arjun
  
stages:
  - Tfvars_Generate
           


- task: TerraformInstaller@1
     inputs:
       terraformVersion: 'latest'

- task: TerraformTask@5
   inputs:
     provider: 'azurerm'
     command: 'init'
     backendServiceArm: 'Arjun-Github-Action'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'custom'
    outputTo: 'console'
    customCommand: 'terraform fmt'
    environmentServiceNameAzureRM: 'Arjun-Github-Action'
